### ISSUE TITLE
Installation instructions for people not familiar with Go?

### ISSUE THREAD

**Issue by alexboss** [danzek/sms-backup-and-restore-parser#1]
Hello,

Thanks for sharing the code of this tool which looks useful.

However, wouldn't it be useful to also provide installation instructions for people not familiar with Go?

Thank you and best regards.

**Comment by danzek** [comment]
Hello @alexboss I originally contemplated having releases for Windows and macOS, but they wouldn't be signed and AV/security vendors would flag it, you'd have to trust I didn't bundle goodies with it, I'd be asked to support those releases if they didn't work after some OS update/upgrade, etc. So I opted to just share the code for folks to do with as they please.

Since the time I wrote this code, Go changed the way it handles modules and so the build process has also changed (i.e., had I provided instructions, they would now be out of date). It used to be really simple: `go get github.com/danzek/sms-backup-and-restore-parser`. But [you can't do that anymore](https://go.dev/doc/go-get-install-deprecation).

With that said, I should update the repo to use the modern modules convention to simplify this. I will do so then post instructions.

**Comment by danzek** [comment]
I added a `go.mod` file to support the updated method of building golang modules (7282fba16ba865c1e8e3f3cec5e8e513aaf72c9b) and I [updated the README to include installation instructions](https://github.com/danzek/sms-backup-and-restore-parser/blob/master/README.md#installation) (4297d0e800704a90e5c2c509ae4a8026c854fb2c).

**Comment by alexboss** [comment]
Thanks @danzek , will give a new try with these updated instructions 👍

**Comment by alexboss** [comment]
Sorry @danzek for the late reply, just to tell you that I gave a try after the feedback you provided, and it works perfectly (on `go version go1.20.4 linux/amd64`).
Thank you for all the effort you put into this, it's great parser and helped me to finally archive my SMS / MMS.
Best regards.
